# Generated by Django 3.1.5 on 2021-04-02 18:21

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=350)),
                ('pub_date', models.DateTimeField(default=timezone.now)),
            ],
        ),
    ]
